global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: ['host.docker.internal:5000'] # your node backend metrics endpoint

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
